### PR TITLE
An attempt to add metatags.

### LINKED ISSUE #1: No metatags
no metatags bruh?? come on this has to be done asap

### PR DESCRIPTION
**Pull request by azidanimoh**
This is my first attempt to add metatags to the website, review please.

### CODE REVIEW

**Review by Salint — CHANGES_REQUESTED** [review]
There are more meta tags than just `description`, [here's a list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name).

**Comment by azidanimoh** [comment]
Trapez asked just for the ``description`` meta tag, dunno the use of other ones for now.

**Comment by Salint** [comment]
Try adding a `theme-color` metatag which sets the color to use for embeds in Discord and URL bar at the top in mobile phones.

**Review by Salint — APPROVED** [review]
Since you aren't adding this, okay then.

**Pull request merged**
